# Generated by Django 5.2.1 on 2025-06-21 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_google_oauth_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='google_oauth_incomplete',
        ),
    ]
