# Generated by Django 5.2.1 on 2025-09-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_customuser_profile_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="attest_professional",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="license_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
